# Generated by Django 4.0.5 on 2022-06-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('what_to_buy', models.CharField(choices=[('FOOD', 'Food'), ('SNACKS', 'Snacks'), ('FOOD STUFF', 'Food stuff'), ('GROCRIES', 'Grocries'), ('DRUGS', 'Drugs'), ('COSMETICS', 'Cosmetics'), ('OTHERS', 'Others')], max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('where_to_buy', models.CharField(choices=[('CAPTAIN COOK', 'Captain Cook'), ('COUNTRY KITCHEN', 'Country Kitchen'), ('ONGBONA', 'Ongbona'), ('IYA RUKA', 'Iya Ruka'), ('MAYFAIR MARKET', 'Mayfair market'), ('SABO MARKET', 'Sabo market'), ('NEW MARKET', 'New market'), ('ACE MALL', 'Ace mall'), ('G2G', 'G2G'), ('PHAIM PHARMACY', 'Phaim pharmacy')], max_length=20)),
                ('delivery_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
    ]
